# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/TracyN/Documents/GitHub/kattis-collatz

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/TracyN/Documents/GitHub/kattis-collatz

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/TracyN/Documents/GitHub/kattis-collatz/CMakeFiles /Users/TracyN/Documents/GitHub/kattis-collatz/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/TracyN/Documents/GitHub/kattis-collatz/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runCollatz

# Build rule for target.
runCollatz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runCollatz
.PHONY : runCollatz

# fast build rule for target.
runCollatz/fast:
	$(MAKE) -f CMakeFiles/runCollatz.dir/build.make CMakeFiles/runCollatz.dir/build
.PHONY : runCollatz/fast

#=============================================================================
# Target rules for targets named old_runCollatz

# Build rule for target.
old_runCollatz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 old_runCollatz
.PHONY : old_runCollatz

# fast build rule for target.
old_runCollatz/fast:
	$(MAKE) -f CMakeFiles/old_runCollatz.dir/build.make CMakeFiles/old_runCollatz.dir/build
.PHONY : old_runCollatz/fast

Collatz.o: Collatz.cpp.o

.PHONY : Collatz.o

# target to build an object file
Collatz.cpp.o:
	$(MAKE) -f CMakeFiles/old_runCollatz.dir/build.make CMakeFiles/old_runCollatz.dir/Collatz.cpp.o
.PHONY : Collatz.cpp.o

Collatz.i: Collatz.cpp.i

.PHONY : Collatz.i

# target to preprocess a source file
Collatz.cpp.i:
	$(MAKE) -f CMakeFiles/old_runCollatz.dir/build.make CMakeFiles/old_runCollatz.dir/Collatz.cpp.i
.PHONY : Collatz.cpp.i

Collatz.s: Collatz.cpp.s

.PHONY : Collatz.s

# target to generate assembly for a file
Collatz.cpp.s:
	$(MAKE) -f CMakeFiles/old_runCollatz.dir/build.make CMakeFiles/old_runCollatz.dir/Collatz.cpp.s
.PHONY : Collatz.cpp.s

KattisCollatz.o: KattisCollatz.cpp.o

.PHONY : KattisCollatz.o

# target to build an object file
KattisCollatz.cpp.o:
	$(MAKE) -f CMakeFiles/runCollatz.dir/build.make CMakeFiles/runCollatz.dir/KattisCollatz.cpp.o
.PHONY : KattisCollatz.cpp.o

KattisCollatz.i: KattisCollatz.cpp.i

.PHONY : KattisCollatz.i

# target to preprocess a source file
KattisCollatz.cpp.i:
	$(MAKE) -f CMakeFiles/runCollatz.dir/build.make CMakeFiles/runCollatz.dir/KattisCollatz.cpp.i
.PHONY : KattisCollatz.cpp.i

KattisCollatz.s: KattisCollatz.cpp.s

.PHONY : KattisCollatz.s

# target to generate assembly for a file
KattisCollatz.cpp.s:
	$(MAKE) -f CMakeFiles/runCollatz.dir/build.make CMakeFiles/runCollatz.dir/KattisCollatz.cpp.s
.PHONY : KattisCollatz.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... runCollatz"
	@echo "... old_runCollatz"
	@echo "... Collatz.o"
	@echo "... Collatz.i"
	@echo "... Collatz.s"
	@echo "... KattisCollatz.o"
	@echo "... KattisCollatz.i"
	@echo "... KattisCollatz.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

